name: documentation

on:
  push:
    branches: [ "main", "Ava-branch-config", "mizuho-githubaction" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: autodoc
        run: echo "Not completed yet"
        # run: npm run autodoc