# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: node

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install required system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++

      - run: npm cache clean --force
      - run: npm ci

      - name: Set config file
        run: cp config.example.ts config.ts

      - name: build
        run: |
          npm run build 2>&1 | tee build-output.log || true

          if grep -q "node_modules/discord.js/typings/index.d.ts" build-output.log; then
            echo "Ignoring build errors from node_modules/discord.js/typings/index.d.ts"
          fi

          if grep -i "error" build-output.log | grep -v "node_modules/discord.js/typings/index.d.ts"; then
            echo "Build failed with unignored errors"
            exit 1
          fi

          echo "No unignored build errors found. Workflow continues."

      - name: Show Jest config
        run: npx jest --showConfig | sed -n '1,120p'

      - name: Run tests (no cache)
        run: npx jest -c jest.config.js --no-cache

      # - name: Start Development
      #   run: npm run dev
