name: dockerimage #name of the workflow

on:
 push:
   branches: [ mizuho ] #which branch to watch for changes

jobs:
 build-and-push:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4

     # 1) Log in to Docker Hub
     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         registry: docker.io
         username: ${{ secrets.DOCKER_USER }} # ← your Docker Hub username
         password: ${{ secrets.DOCKER_PASSWORD }} # ← your Docker Hub password

     # 2) Build & push
     - name: Build and push Docker image
       uses: docker/build-push-action@v3
       with:
         context: .
         push: true                   # ← enable push
         tags: jun332/jun_131:main  # ← your repo/image name